### ISSUE TITLE
加个短信转发

### ISSUE THREAD

**Issue by aohanhongzhi** [aohanhongzhi/android_packages_apps_Messaging#1]
底层代码加一个网络请求转发即可，但是目前网络请求不能写在主方法里面。需要弄个Service。
`dRuntime: FATAL EXCEPTION: main
05-13 18:50:44.207  4318  4318 E AndroidRuntime: Process: com.android.messaging, PID: 4318
05-13 18:50:44.207  4318  4318 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.android.messaging.receiver.SmsDeliverReceiver: android.os.NetworkOnMainThreadException
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4384)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7871)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: Caused by: android.os.NetworkOnMainThreadException
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1651)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.messaging.receiver.HttpClient.doGet(SourceFile:6)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.messaging.receiver.SmsReceiver.deliverSmsIntent(SourceFile:9)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at com.android.messaging.receiver.SmsDeliverReceiver.onReceive(SourceFile:1)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4375)
05-13 18:50:44.207  4318  4318 E AndroidRuntime: 	... 9 more
`

**Comment by aohanhongzhi** [comment]
05-14 00:27:20.959  1832  1832 I MessagingApp: 接收短信完整信息: 
05-14 00:27:20.959  1832  1832 I MessagingApp: 尊敬的客户：截止至2022年05月14日，您账户当前结余31.49元（=可用余额33.47元-本月未出账费用1.98元）。充值卡交费请回复7，查询流量请回复1081。
05-14 00:27:20.959  1832  1832 I MessagingApp: 更多信息请下载“安徽掌上10000”（ http://t.cn/RvbDYPp ）或微信关注“安徽电信”公众号，查询办理更方便！-安徽电信
05-14 00:27:20.960  1504  2607 W ActivityManager: Unable to start service Intent { cmp=com.android.messaging/.receiver.SyncIntentService (has extras) } U=0: not found
05-14 00:27:20.962  1832  1832 V MessagingApp: SmsReceiver.deliverSmsMessages

**Comment by aohanhongzhi** [comment]
解决方案
https://blog.csdn.net/weixin_43876206/article/details/103497419

应用网络权限

`05-14 11:05:03.522  9892  9892 I MessagingApp: 接收短信完整信息: 
05-14 11:05:03.522  9892  9892 I MessagingApp: 尊敬的客户：截止至2022年05月14日，您账户当前结余31.49元（=可用余额33.47元-本月未出账费用1.98元）。充值卡交费请回复7，查询流量请回复1081。
05-14 11:05:03.522  9892  9892 I MessagingApp: 更多信息请下载“安徽掌上10000”（ http://t.cn/RvbDYPp ）或微信关注“安徽电信”公众号，查询办理更方便！-安徽电信
05-14 11:05:03.526  9892  9892 I MessagingApp: 计划发送到服务器
05-14 11:05:03.528  9892  9892 V MessagingApp: SmsReceiver.deliverSmsMessages
05-14 11:05:03.538  9892  8380 I MessagingApp: 子服务里面处理消息尊敬的客户：截止至2022年05月14日，您账户当前结余31.49元（=可用余额33.47元-本月未出账费用1.98元）。充值卡交费请回复7，查询流量请回复1081。
05-14 11:05:03.538  9892  8380 I MessagingApp: 更多信息请下载“安徽掌上10000”（ http://t.cn/RvbDYPp ）或微信关注“安徽电信”公众号，查询办理更方便！-安徽电信
05-14 11:05:03.539  9892  8380 W System.err: java.io.IOException: Cleartext HTTP traffic to easyprint.vip not permitted
05-14 11:05:03.539  9892  8380 W System.err: 	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:127)
05-14 11:05:03.539  9892  8380 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
05-14 11:05:03.539  9892  8380 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
05-14 11:05:03.539  9892  8380 W System.err: 	at com.android.messaging.receiver.HttpClient.doGet(SourceFile:6)
05-14 11:05:03.540  9892  8380 W System.err: 	at com.android.messaging.receiver.SyncIntentService.onHandleIntent(SourceFile:4)
05-14 11:05:03.540  9892  8380 W System.err: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
05-14 11:05:03.540  9892  8380 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-14 11:05:03.540  9892  8380 W System.err: 	at android.os.Looper.loopOnce(Looper.java:201)
05-14 11:05:03.540  9892  8380 W System.err: 	at android.os.Looper.loop(Looper.java:288)
05-14 11:05:03.540  9892  8380 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by aohanhongzhi** [comment]
功能完成！

**Comment by aohanhongzhi** [comment]
`App: DraftMessageData: set selfId=1 for conversationId=5
06-13 20:00:30.339  3380 10191 I MessagingAppDataModel: ReceiveSmsMessageAction: Received SMS message 23 in conversation 5, uri = content://sms/22
06-13 20:00:30.339  3380 10191 I MessagingAppDataModel: ProcessPendingMessagesAction: Scheduling pending messages for subId 2
06-13 20:00:30.347  3380 10191 I MessagingAppDataModel: ProcessPendingMessagesAction: Start queueing for subId 2
06-13 20:00:30.349  3380 10191 I MessagingAppDataModel: ProcessPendingMessagesAction: No messages to send or download
06-13 20:00:30.366  3380 10198 W MessagingApp: error loading sound for content://settings/system/notification_sound
06-13 20:00:30.366  3380 10198 W MessagingApp: java.lang.SecurityException: getDefaultOutgoingPhoneAccount: Neither user 10102 nor current process has android.permission.READ_PRIVILEGED_PHONE_STATE.
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.os.Parcel.createException(Parcel.java:2410)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.os.Parcel.readException(Parcel.java:2393)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.os.Parcel.readException(Parcel.java:2335)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at com.android.internal.telecom.ITelecomService$Stub$Proxy.getUserSelectedOutgoingPhoneAccount(ITelecomService.java:1750)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.telecom.TelecomManager.getUserSelectedOutgoingPhoneAccount(TelecomManager.java:1144)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.media.RingtoneManager.getDefaultPhoneAccountHandle(RingtoneManager.java:899)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.media.RingtoneManager.getCacheForType(RingtoneManager.java:1060)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1088)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1027)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at com.android.messaging.util.NotificationPlayer$CreationAndCompletionThread.run(SourceFile:8)
06-13 20:00:30.366  3380 10198 W MessagingApp: Caused by: android.os.RemoteException: Remote stack trace:
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.app.ContextImpl.enforce(ContextImpl.java:2217)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2245)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:905)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at com.android.server.telecom.TelecomServiceImpl.isDialerOrPrivileged(TelecomServiceImpl.java:2435)
06-13 20:00:30.366  3380 10198 W MessagingApp: 	at com.android.server.telecom.TelecomServiceImpl.access$400(TelecomServiceImpl.java:78)`
